language: python
python:
    - '3.3'
    - '3.4'
    - '3.5'

# commands to install dependencies
install:
    - python setup.py --quiet install

# commands to run tests
script:
    # Remove the outdated packages that Travis provides so it can install the
    # version of pytest that hangups requires.
    - pip uninstall --quiet --yes pytest py
    - python setup.py --quiet style
    - python setup.py --quiet lint
    - python setup.py --quiet test
    - pip install --quiet docutils
    # This check fails on Travis with older versions of Python for some reason.
    - if [[ $TRAVIS_PYTHON_VERSION = '3.5' ]]; then python setup.py check --metadata --restructuredtext --strict; fi

# allow container-based infrastructure
sudo: false
