language: python
python:
    - '3.3'
    - '3.4'
    - 'pypy3'
install:
    - python setup.py install
script:
    - python setup.py test
    - pip install docutils
    - python setup.py check --metadata --restructuredtext --strict
