language: python
python:
    - '3.3'
    - '3.4'
install:
    - python setup.py install
script:
    - python setup.py --quiet test
    - pip install --quiet docutils
    - python setup.py check --metadata --restructuredtext --strict
